---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [gethnet/main]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check config
        uses: home-assistant/actions/addon-check@master

      - name: Build test
        uses: home-assistant/actions/addon-build@master
        with:
          arch: amd64
          addon: vscode
