---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Addon
        uses: home-assistant/actions/addon-publish@master
        with:
          ignore_images: true
          registry: ghcr.io
          repository: ${{ github.repository_owner }}/vscode-fork
          addon: vscode
          arch: |
            - aarch64
            - amd64
